### ISSUE TITLE
Assets organization/categorizing.

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet-cms-boilerplate#29]
As a user builds out more content within their CMS I see the Assets functionality getting quite cumbersome. Brand Central alone will have a couple hundred assets. Let's consider our options for categorizing Assets.

**Comment by RyanCCollins** [comment]
I've taken care of this on the brand-central branch.  Assets are now loaded with the onMore pagination for lists, so that the user can scroll to load more.  We can work on further organization if need be.
