### ISSUE TITLE
Add layout to cms

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet-cms-boilerplate#56]
I hate to say this but the more I think about it, the more I am realizing that we will need control over layout. 

I've thought of an option that does not require nesting of content blocks (maybe).  With the new refactor, content blocks are now stored in sections.  What if we added a few layout related properties (basis, padding, etc) to each section and then dynamically render the grommet section components layout. 

The other option is to add a generic Box content block that serves as the only content block that can be nested.

**Comment by RyanCCollins** [comment]
Here is what I've come up with for the type of properties to store to achieve the MVP for a dynamic layout engine:

```
export type LayoutProps = {
  children: React$Element<any> | HTMLElement,
  section: {
    basis?: "xsmall" | "small" | "medium" | "large" | "xlarge" | "xxlarge" | "full" | "1/2" | "1/3" | "2/3" | "1/4" | "3/4",
    pad?: "small" | "medium" | "large" | "none",
    direction?: "row" | "column",
    wrap?: boolean,
    justifyContent?: string,
    alignItems?: string
  },
  box: {
    pad?: "small" | "medium" | "large" | "none",
    size?: 'auto' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | 'xxlarge' | 'full',
    flex?: "grow" | "shrink" | boolean
  }
}
```

**Comment by karatechops** [comment]
This makes sense to me, it might be a bit granular - have you discovered use cases for all the options? 

My worry is providing a non-technical user with too many options. What if we hid the layout options until the user checked an advanced layout option? For instance, with Brand Central, I don't believe a technical user with flex-box experience will be adding new content. 

@MikeWalrath do you have any input here?

**Comment by RyanCCollins** [comment]
Yeah that seems like a good idea.  The issue that I was finding without being able to control the layout of the section and the box that surrounds each content block, we might as well not have any layout options.  I would like to try to arrive at a more basic version of this while still having the capability to control the layout in a granular way.  I think what would make the most sense is to implement this and then play with it.  That will help us all determine which properties are must haves, nice to have, or not needed.

**Comment by karatechops** [comment]
Sounds good to me. I like the idea of packaged layouts (layout blocks!?).  😄

**Comment by RyanCCollins** [comment]
Done in #64
