### ISSUE TITLE
Content block specification

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet-cms-boilerplate#60]
We discussed potentially making the content-blocks a separate module that could make the whole cms more pluggable.  Let's use this as a forum to develop a specification for this.  We will call this a feature of version 2 as we probably will not be able to do this right away.

**Comment by RyanCCollins** [comment]
Each content block needs the following:
1. Preview (right now this is not used though, so maybe this is not a part of the spec?)
2. Rendered content
3. Form

**Comment by karatechops** [comment]
I like the thumbnail/wireframe so you get a quick idea of what you're getting. Title should probably be on there as well.

**Comment by RyanCCollins** [comment]
Hmm, yeah I can see the preview still being useful.  The way that I've handled it to make the UI more like the mockups is to have only one generic preview component that all types use.  Still, I think you're right that the preview should be a part of the spec.

**Comment by RyanCCollins** [comment]
So I've got the majority of this figured out.  What I think we should plan to do in the future is to move all the components of the content block (i.e. Form, BlockMap) into one place.  That way we can keep things modular and decoupled so that we can work to having a more straightforward mechanism for installing content blocks from npm, or another library.

**Comment by RyanCCollins** [comment]
Closing, but we will reference this at a later time.
